export {GAME_INTERNAL_RESOLUTION_SCALE,CHARACTER_OUTLINE_BASE_WIDTH,CHARACTER_OUTLINE_BASE_COLOR,CHARACTER_SEPARATOR_BASE_WIDTH,CHARACTER_SEPARATOR_BASE_COLOR,CHARACTER_CONTACT_SHADOW_COLOR,CHARACTER_CONTACT_SHADOW_ALPHA_SCALE} from '../../packages/field-renderer/render-constants.mjs';
/** 검수에서 채택한 표시 크기와 독립적인 렌더링 기준값. */
